---

- name: Include OS-specific Vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install KernelCare
  package:
    name="{{ kernelcare_package }}"
    state="present"

- name: Install License Key
  command: kcarectl --register "{{ kernelcare_key }}"
  when: kernelcare_key != ""
